name: Build & Test Fedora Minimal

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

## Build ##

jobs:
  linux-fedora-minimal:
    name: Build with minimal configuration on Fedora Linux
    runs-on: ubuntu-latest
    container: sogno/dpsim:dev-minimal
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Create Build Environment
      run: mkdir build

    - name: Cache build directory
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/build
        key: build-cache-fedora-minimal-${{ github.ref }}

    - name: Configure CMake
      shell: bash
      working-directory: ${{ github.workspace }}/build
      run: cmake -DFETCH_SPDLOG=ON $GITHUB_WORKSPACE

    - name: Build every target
      shell: bash
      working-directory: ${{ github.workspace }}/build
      run: cmake --build . --parallel $(nproc)

## Tests ##
  #TODO
